[project]
name = "baseline-single"
version = "0.1.0"
description = "Baseline single-request inference service"
dependencies = [
    "fastapi",
    "uvicorn[standard]", 
    "sse-starlette",
    "llama-cpp-python",
]

[project.scripts]
serve = "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"